name: NightVision
main: nl.galaxias.nightvision.NightVision
version: 1.0

commands:
   nv:
      description: Turn on Night Vision
      usage: /<command> toggle [duration]
      permission: nightvision.toggle
      permission-message: You don't have <permission>

permissions:
    nightvision.toggle:
        description: Allows you use /nv
        default: op